# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
    # Schedule updates (each 4 hours)
    schedule: [{ cron: "0 */8 * * *" }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ["anime"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@master
              with:
                  # Your GitHub token
                  # The following scopes are required:
                  #  - public_access (default scope)
                  #  - repo
                  # The following additional scopes may be required:
                  #  - read:org      (for organization related metrics)
                  #  - read:user     (for user related data)
                  #  - read:packages (for some packages related data)
                  #  - repo          (optional, if you want to include private repositories)
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: ranfey
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_hireable: yes
                  config_octicon: yes
                  config_timezone: Asia/Shanghai

                  #   plugin_people: yes
                  #   plugin_people_limit: 24
                  #   plugin_people_size: 28
                  #   plugin_people_types: followers, following


                  # plugin_calendar: yes
                  # plugin_calendar_limit: 2

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: half-year

                  # plugin_introduction: yes
                  # plugin_introduction_title: yes

                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_ignored: Mathematica, Jupyter Notebook, Starlark, BibTeX Style, Tex, Shell
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%

                  plugin_lines: yes
                  plugin_lines_history_limit: 1
                  plugin_lines_repositories_limit: 4
                  plugin_lines_sections: base

                  plugin_traffic: yes

                  #   plugin_followup: yes
                  #   plugin_followup_archived: yes
                  #   plugin_followup_indepth: no
                  #   plugin_followup_sections: repositories

                  #   plugin_notable: yes
                  #   plugin_notable_from: all
                  #   plugin_notable_types: commit

